### PR TITLE
Issue #135 and Fixed errors in Last pull request #137

### PR DESCRIPTION
**Pull request by pahnin**
Please see the commit message
https://github.com/pahnin/goldberg/commit/82916daa839c9f0e539f558b3a4c1626807c7435

### CODE REVIEW

**Comment by pahnin** [comment]
any problem with this pull-request?

**Comment by srushti** [comment]
Everything looks fine and I'll merge it in today, and identify more stories for you to work on. In the future, I'd suggest you make these changes and raise pull requests from a branch. Project timelines (me included) tend to squash commits to clean up their timeline & maybe even rebase. As it stands, once I merge it you will probably have to delete your app and reclone or at least delete master and recreate it.

**Comment by pahnin** [comment]
Ok. Thanks.

**Comment by srushti** [comment]
Merged (93f78ada5e0eadece9fabc1b49082dfb2d4e0518).

**Pull request closed without merging**
