### PR TITLE
Goldberg start command now daemonizes. Added stop command.

### PR DESCRIPTION
**Pull request by drewolson**
I updated the goldberg start command to daemonize the process using the rackup -D flag and write a pid file using the rackup -P flag. I also added a goldberg stop command which kills the daemonized process using the pid file.

Hope you like what you see!
- Drew

### CODE REVIEW

**Comment by srushti** [comment]
Looks good. We've moved to using the commander gem to hand the command-line options. Could you merge latest (moving 'stop' to the new 'bin/goldberg', of course) and give us another pull request.

**Comment by kaiwren** [comment]
@srushti Checking in to the branch against which this pull request was created updates the pull request, so you don't have to create a new one.

**Comment by drewolson** [comment]
I've rebased my master on your latest master and updated my stop command to use commander. Let me know if any other changes are needed before pulling this in.

Thanks,
Drew

**Comment by srushti** [comment]
Thanks. I've merged in the changes. I haven't tested this extensively, but it looks good for now.

**Pull request merged**
