### PR TITLE
Displaying author for the checkin that broke the build issue #92

### PR DESCRIPTION
**Pull request by suryagaddipati**

### CODE REVIEW

**Comment by srushti** [comment]
Looks pretty good. One thing I'd like is to list all the people who have committed to that specific build, not just the very last committer. Any of those commits could have failed the build.

**Comment by suryagaddipati** [comment]
@srushti  ha, yes I agree. Let me see how i could get that in.

**Comment by suryagaddipati** [comment]
@srushti i took a shot a displaying all the authors who might have caused the build to fail. Could you take a look.

**Comment by srushti** [comment]
@suryagaddipati I took a look, and I was looking for a clarification. You seem to have handled the problem where the build has broken multiple times, with different committers. Does it handle the issue where there are multiple committers on one single build? At first glance it doesn't look like it. If you tell me it does, I'll look at it more closely.

**Comment by suryagaddipati** [comment]
@srushti yes it does. I just realized that the method should have been called "revision_range" instead or "build_range".
Let me rename the method and submit it.

**Comment by srushti** [comment]
Is there any progress on this? If not, I'm happy to pick up the last bit and finish it. Let me know either way.

**Comment by suryagaddipati** [comment]
@srushti I was out on vacation. will submit it in a day or two.

**Comment by srushti** [comment]
Sure, no problem. Just let me know if you won't be working on it, and I can pick it up.

**Comment by suryagaddipati** [comment]
I've changed the the method name to match what its doing. Please take a look and let me know what you think.

**Comment by srushti** [comment]
Thanks. It's been merged in. I haven't had a chance to test it yet, but I'm assuming it's fine.

**Pull request closed without merging**
