### PR TITLE
Move build status image above header in Readme for more prominence

### PR DESCRIPTION
**Pull request by ghost**
I think it looks a lot better and is more prominent above the header.

On a related note you can also add dependency status using https://gemnasium.com

### CODE REVIEW

**Comment by srushti** [comment]
It's merged. Also, what's the value of adding gemnasium to the README? Who would care?

**Comment by ghost** [comment]
The developers of Goldberg? :) Not important, just a suggestion, obviously not a well thought out one! :P

Umm why is the build image broken on the Readme? Did I break something?

**Comment by ghost** [comment]
It's because of this: https://github.com/blog/743-sidejack-prevention-phase-3-ssl-proxied-assets

For some reason the camo thingy isn't working properly and points to https://camo.githubapp.com/94a4debe06f0afa17d9cbc0ced1b2f21da528478/687474703a2f2f63692e6334322e696e2f70726f6a656374732f676f6c64626572672e706e67 leading to no image for build status :(

**Comment by srushti** [comment]
We had the same problem when we first added it. Eventually it started showing up. I'm not sure if it refreshes too frequently though. I think travis-ci has the same problem.

**Comment by ghost** [comment]
Ah ok that explains it then. Re: Travis, they are using a https url for images ex: https://secure.travis-ci.org/carlhuda/bundler.png?branch=master so they don't have that problem anymore.

**Pull request merged**
